import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {workspacePage} from './workspace-test.mjs';
const require=createRequire(new URL('../../study-log-web/package.json',import.meta.url)),er=createRequire(new URL('./package.json',import.meta.url));const {_electron:electron,expect}=require('@playwright/test');
const evidence=path.resolve('.local',`layout-${Date.now()}`);await fs.mkdir(evidence);const env={...process.env,STUDY_LOG_DESKTOP_PROFILE:await fs.mkdtemp(path.join(os.tmpdir(),'layout-check-'))};delete env.ELECTRON_RUN_AS_NODE;
const app=await electron.launch({executablePath:process.argv[2]||er('electron'),args:process.argv[2]?[]:[path.resolve('ops/electron')],env});
try{const page=await workspacePage(app);const titlebar=app.context().pages().find(p=>p.url().includes('titlebar.html'));await expect(titlebar.locator('#location')).toHaveText('本地使用');const overflow=()=>page.evaluate(()=>({height:innerHeight,scroll:document.documentElement.scrollHeight,items:[...document.querySelectorAll('.app-shell,.workspace,.writing-inspector,.reader,.sidebar')].map(e=>({name:e.className,top:e.getBoundingClientRect().top,height:e.getBoundingClientRect().height}))}));console.log(JSON.stringify(await overflow()));

for(const theme of ['日间','夜间']){await page.getByRole('button',{name:'切换主题模式',exact:true}).click();await page.locator('.theme-popover').getByRole('button',{name:theme+'模式',exact:true}).click();for(const expanded of [false,true]){if(expanded)await page.getByRole('button',{name:'展开右侧栏',exact:true}).click();const m=await overflow();console.log(theme,expanded,JSON.stringify(m));assert.ok(m.scroll<=m.height+1,'workspace outer overflow');await expect.poll(()=>page.locator('.writing-inspector').evaluate(e=>Math.abs(innerWidth-e.getBoundingClientRect().right)),{message:'right sidebar must meet viewport edge after transition'}).toBeLessThanOrEqual(1);if(expanded){await expect.poll(()=>page.locator('#writing-instruction').evaluate(e=>e.scrollHeight-e.clientHeight)).toBeLessThanOrEqual(1);const input=await page.locator('#writing-instruction').evaluate(e=>({scroll:e.scrollHeight,client:e.clientHeight,offset:e.offsetHeight,style:e.style.height,min:getComputedStyle(e).minHeight,flex:getComputedStyle(e).flexShrink}));console.log('instruction',input);assert.ok(input.scroll<=input.client+1,'empty instruction overflow');}const color=await page.locator('.writing-inspector').evaluate((e,expanded)=>({actual:getComputedStyle(e).backgroundColor,expected:getComputedStyle(document.documentElement).getPropertyValue(expanded?'--canvas':'--surface-soft').trim()}),expanded);assert.equal(color.actual,await page.evaluate(hex=>{const e=document.createElement('span');e.style.color=hex;document.body.append(e);const c=getComputedStyle(e).color;e.remove();return c;},color.expected));await page.screenshot({path:path.join(evidence,`${theme}-${expanded}.png`)});if(expanded){const panel=page.locator('.writing-panel');assert.ok(await panel.evaluate(e=>e.scrollHeight>e.clientHeight),'long panel retains scrolling');await panel.evaluate(e=>e.scrollTop=e.scrollHeight);assert.ok(await panel.evaluate(e=>e.scrollTop>0));}if(expanded)await page.getByRole('button',{name:'折叠右侧栏',exact:true}).click();}}
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1280,720));await expect.poll(()=>page.evaluate(()=>innerHeight)).toBe(684);assert.ok((await overflow()).scroll<=684+1);
await app.evaluate(({Menu})=>Menu.getApplicationMenu().items[0].submenu.items.find(i=>i.label==='使用方式…').click());await expect.poll(()=>app.context().pages().some(p=>p.url().includes('connection.html'))).toBe(true);const c=app.context().pages().find(p=>p.url().includes('connection.html'));await c.locator('[value=remote]').check();const geometry=await c.evaluate(()=>({height:innerHeight,scroll:document.documentElement.scrollHeight}));console.log(geometry);assert.ok(geometry.scroll<=geometry.height+1,'connection overflow');await c.screenshot({path:path.join(evidence,'connection.png')});await c.getByRole('button',{name:'取消',exact:true}).click();await fs.writeFile(path.join(evidence,'report.json'),JSON.stringify({passed:true,geometry}));console.log(evidence);
}finally{const closed=app.waitForEvent('close',{timeout:60000});await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().forEach(w=>w.close()));await closed;}
