import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { parseEnv } from 'node:util';
import { createRequire } from 'node:module';
const require = createRequire(new URL('../study-log-web/package.json', import.meta.url));
const { chromium, expect } = require('@playwright/test');
const AdmZip = require('adm-zip');
const [root, base = 'http://127.0.0.1:3561/study-log'] = process.argv.slice(2);
if (!root || !path.isAbsolute(root) || !['localhost', '127.0.0.1'].includes(new URL(base).hostname)) throw Error('Local synthetic fixture required');
const env = parseEnv(await fs.readFile(path.join(root, '.env'), 'utf8'));
const output = path.resolve('artifacts/export');
await fs.mkdir(output, { recursive: true });
const browser = await chromium.launch();
const date = '2026-09-12', noteTitle = '导出验收独立随记';
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  page.setDefaultTimeout(15000);
  const errors = [], downloads = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('download', download => downloads.push(download));
  const login = async () => {
    await page.getByLabel('访问密码').fill(env.APP_PASSWORD);
    await page.getByRole('button', { name: '登录', exact: true }).click();
    await expect(page.locator('.workspace')).toBeVisible();
  };
  const choose = async label => {
    const more = page.getByRole('button', { name: '更多日志操作', exact: true });
    if (await more.isVisible()) {
      await more.click();
      await page.getByRole('dialog', { name: '日志操作', exact: true }).getByRole('button', { name: label, exact: true }).click();
    } else {
      await page.getByRole('button', { name: '导出', exact: true }).filter({ visible: true }).click();
      await page.getByRole('menuitem', { name: label, exact: true }).click();
    }
  };
  const confirm = async () => {
    await page.getByRole('alertdialog', { name: '导出已保存内容？' }).getByRole('button', { name: '继续导出' }).click();
    await expect(page.getByRole('alertdialog', { name: '导出已保存内容？' })).toHaveCount(0);
  };
  const saveDownload = async (action, name) => {
    const pending = page.waitForEvent('download');
    await action();
    const download = await pending;
    assert.equal(await download.failure(), null);
    const file = path.join(output, name + '.zip');
    await download.saveAs(file);
    const zip = new AdmZip(file);
    return { suggestedName: download.suggestedFilename(), entries: zip.getEntries().filter(entry => !entry.isDirectory), zip };
  };
  const markdown = archive => archive.entries.filter(entry => entry.entryName.endsWith('.md')).map(entry => entry.getData().toString('utf8')).join('\n');
  await page.goto(base); await login();
  const image = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="80" height="40"><text y="24">Export</text></svg>');
  const upload = await page.request.post(base + '/api/assets/upload', { multipart: { scope: 'logs', file: { name: '导出附件.svg', mimeType: 'image/svg+xml', buffer: image } } });
  assert.equal(upload.status(), 200);
  const asset = (await upload.json()).assets[0];
  const saved = `### 导出验收\n\nEXPORT_SAVED_ONLY 中文正文。\n\n${asset.markdown}\n\n![缺失附件](./assets/export-missing-fixture.png)\n\n\`\`\`js\nconsole.log('export');\n\`\`\``;
  const { day } = await (await page.request.get(base + '/api/logs/day?date=' + date)).json();
  assert.equal((await page.request.put(base + '/api/logs/day', { data: { date, content: saved, baseVersion: day.version } })).status(), 200);
  const before = (await (await page.request.get(base + '/api/logs/day?date=' + date)).json()).day;
  const notes = (await (await page.request.get(base + '/api/notes')).json()).notes;
  for (const note of notes.filter(note => note.title === noteTitle)) assert.equal((await page.request.delete(base + '/api/notes', { data: { id: note.id, baseVersion: note.version } })).status(), 200);
  const noteCreated = await page.request.post(base + '/api/notes', { data: { title: noteTitle, body: 'EXPORT_NOTE_SAVED 中文随记。', insight: '验收理解', sources: ['合成来源'], tags: ['导出验收'], recordedAt: date + 'T10:00' } });
  assert.equal(noteCreated.status(), 200);
  await page.goto(base + '?date=' + date);
  await page.getByRole('button', { name: '源码', exact: true }).filter({ visible: true }).click();
  const editor = page.locator('.cm-content');
  await editor.click(); await editor.press('Control+End'); await page.keyboard.insertText('\n\nEXPORT_UNSAVED_DRAFT');
  await choose('当前日块');
  await page.getByRole('alertdialog', { name: '导出已保存内容？' }).getByRole('button', { name: '取消', exact: true }).click();
  await expect(page.getByRole('alertdialog', { name: '导出已保存内容？' })).toHaveCount(0);
  assert.equal(downloads.length, 0);
  await expect(editor).toContainText('EXPORT_UNSAVED_DRAFT');
  const daily = await saveDownload(async () => { await choose('当前日块'); await confirm(); }, 'day');
  assert.equal(daily.suggestedName, date + '.zip');
  assert.match(markdown(daily), /EXPORT_SAVED_ONLY/); assert.doesNotMatch(markdown(daily), /EXPORT_UNSAVED_DRAFT/);
  assert.deepEqual(daily.entries.find(entry => entry.entryName.endsWith('/assets/' + asset.fileName)).getData(), image);
  assert.match(daily.entries.find(entry => entry.entryName.endsWith('/导出说明.txt')).getData().toString('utf8'), /export-missing-fixture/);
  await expect(page.getByText(/个附件缺失，请查看 ZIP/)).toBeVisible();
  await expect(editor).toContainText('EXPORT_UNSAVED_DRAFT');
  assert.equal((await (await page.request.get(base + '/api/logs/day?date=' + date)).json()).day.version, before.version);
  for (const [label, file] of [['当前源文件', 'file'], ['全部日志', 'all']]) {
    const archive = await saveDownload(async () => { await choose(label); await confirm(); }, file);
    assert.match(markdown(archive), /EXPORT_SAVED_ONLY/); assert.doesNotMatch(markdown(archive), /EXPORT_UNSAVED_DRAFT|EXPORT_NOTE_SAVED/);
    assert.equal(archive.entries.some(entry => /随记|\.env|favorites|sessions/.test(entry.entryName)), false);
    if (file === 'file') assert.match(archive.suggestedName, /学习日志\.zip$/);
    assert.deepEqual(archive.entries.find(entry => entry.entryName.endsWith('/assets/' + asset.fileName)).getData(), image);
  }
  await page.route('**/api/export?**', route => route.fulfill({ status: 500, json: { error: '合成导出失败' } }));
  await choose('当前日块'); await confirm(); await expect(page.getByText('合成导出失败', { exact: true })).toBeVisible();
  await page.unroute('**/api/export?**');
  await saveDownload(async () => { await choose('当前日块'); await confirm(); }, 'retry');
  // A cancelled request may still finish on the server; it must not download or block retry.
  let cancelRelease, cancelStarted, cancelFinished;
  const cancelGate = new Promise(resolve => { cancelRelease = resolve; });
  const cancelSeen = new Promise(resolve => { cancelStarted = resolve; });
  const cancelledFinished = new Promise(resolve => { cancelFinished = resolve; });
  const beforeCancel = downloads.length;
  await page.route('**/api/export?**', async route => {
    const response = await route.fetch(); cancelStarted(); await cancelGate;
    await route.fulfill({ response }).catch(() => {}); cancelFinished();
  });
  await choose('当前日块'); await confirm(); await cancelSeen;
  await page.getByRole('button', { name: '取消导出', exact: true }).click();
  await expect(page.getByRole('button', { name: '导出', exact: true }).filter({ visible: true })).toBeEnabled();
  cancelRelease(); await cancelledFinished; await page.unroute('**/api/export?**');
  assert.equal(downloads.length, beforeCancel);
  await saveDownload(async () => { await choose('当前日块'); await confirm(); }, 'cancel-retry');
  await page.route('**/api/export?**', route => route.fulfill({ status: 401, json: { error: 'Unauthorized' } }));
  await choose('当前日块'); await confirm(); await expect(page.getByLabel('访问密码')).toBeVisible();
  await page.unroute('**/api/export?**'); await login(); await expect(editor).toContainText('EXPORT_UNSAVED_DRAFT');
  await saveDownload(async () => { await choose('当前日块'); await confirm(); }, 'reauth');
  const count = downloads.length;
  await choose('当前日块');
  await expect(page.getByRole('alertdialog', { name: '导出已保存内容？' })).toBeVisible();
  await page.evaluate(() => window.dispatchEvent(new Event('study-log:auth-expired')));
  await login(); await expect(page.getByRole('alertdialog', { name: '导出已保存内容？' })).toHaveCount(0);
  assert.equal(downloads.length, count);
  let release, started;
  const gate = new Promise(resolve => { release = resolve; }), seen = new Promise(resolve => { started = resolve; });
  await page.route('**/api/export?**', async route => { const response = await route.fetch(); started(); await gate; await route.fulfill({ response }).catch(() => {}); });
  await choose('当前日块'); await confirm(); await seen;
  await page.evaluate(() => window.dispatchEvent(new Event('study-log:auth-expired'))); await login(); release();
  await page.unroute('**/api/export?**');
  await expect(editor).toContainText('EXPORT_UNSAVED_DRAFT');
  await page.getByRole('button', { name: '导出', exact: true }).filter({ visible: true }).click();
  await expect(page.getByRole('menu', { name: '导出范围' })).toBeVisible();
  await page.screenshot({ path: path.join(output, 'desktop.png') });
  await page.keyboard.press('Escape'); assert.equal(downloads.length, count);
  await page.setViewportSize({ width: 390, height: 844 });
  const mobile = await saveDownload(async () => { await choose('导出当前日块'); await confirm(); }, 'mobile');
  assert.match(markdown(mobile), /EXPORT_SAVED_ONLY/); assert.doesNotMatch(markdown(mobile), /EXPORT_UNSAVED_DRAFT/);
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: path.join(output, 'mobile.png') });
  // Reload only the synthetic fixture to discard our test draft before checking the independent notes scope.
  await page.goto(base + '?date=' + date); await page.setViewportSize({ width: 1440, height: 900 });
  let moduleRelease, moduleStarted, moduleFinished;
  const moduleGate = new Promise(resolve => { moduleRelease = resolve; });
  const moduleSeen = new Promise(resolve => { moduleStarted = resolve; });
  const moduleDone = new Promise(resolve => { moduleFinished = resolve; });
  const beforeModule = downloads.length;
  await page.route('**/api/export?**', async route => {
    const response = await route.fetch(); moduleStarted(); await moduleGate;
    await route.fulfill({ response }).catch(() => {}); moduleFinished();
  });
  await choose('当前日块'); await moduleSeen;
  await page.getByRole('button', { name: '随记', exact: true }).filter({ visible: true }).first().click();
  await expect(page.getByLabel('搜索随记', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '取消导出', exact: true })).toHaveCount(0);
  moduleRelease(); await moduleDone; await page.unroute('**/api/export?**');
  assert.equal(downloads.length, beforeModule);
  const card = page.locator('.note-entry').filter({ has: page.getByRole('heading', { name: noteTitle, exact: true }) });
  await card.getByRole('button', { name: '编辑', exact: true }).click();
  const noteBody = page.getByLabel('随记正文', { exact: true }); await noteBody.fill('EXPORT_NOTE_UNSAVED');
  const noteArchive = await saveDownload(async () => { await choose('全部随记'); await confirm(); }, 'notes');
  assert.match(markdown(noteArchive), /EXPORT_NOTE_SAVED/); assert.doesNotMatch(markdown(noteArchive), /EXPORT_NOTE_UNSAVED|<!--\s*study-note\s/);
  assert.equal(noteArchive.entries.some(entry => /学习日志\.md$/.test(entry.entryName)), false);
  await expect(noteBody).toHaveValue('EXPORT_NOTE_UNSAVED');
  assert.deepEqual(errors, []);
  console.log('Passed: four real toolbar ZIP downloads and extracted contents; assets, Chinese filenames, missing warnings; draft preservation/cancel; failure retry; authentication epochs; desktop/mobile.');
} finally { await browser.close(); }
