import fs from "node:fs/promises";
import path from "node:path";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import { parseEnv } from "node:util";

const [root, base = "http://127.0.0.1:3561/study-log"] = process.argv.slice(2);
if (!root || !path.isAbsolute(root) || !["127.0.0.1", "localhost"].includes(new URL(base).hostname)) throw new Error("Use a local synthetic reading fixture");
const env = parseEnv(await fs.readFile(path.join(root, ".env"), "utf8"));
const files = (await fs.readdir(path.join(root, "data"))).filter(name => name.endsWith(".md"));
const digests = async () => Promise.all(files.map(async name => crypto.createHash("sha256").update(await fs.readFile(path.join(root, "data", name))).digest("hex")));
const before = await digests();
const auth = await fetch(base + "/api/auth/app-login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password: env.APP_PASSWORD }) });
const { token } = await auth.json();
const headers = { authorization: `Bearer ${token}` };
const get = route => fetch(base + route, { headers });
assert.equal((await fetch(base + "/api/logs/months")).status, 401);
const months = await get("/api/logs/months");
assert.match(months.headers.get("cache-control"), /no-store/);
assert.deepEqual((await months.json()).months.map(m => [m.id, m.dayCount]), [["2026-02", 1], ["2026-01", 2], ["2025-12", 1]]);
const days = await (await get("/api/logs?month=2026-01")).json();
assert.deepEqual(days.days.map(d => d.date), ["2026-01-17", "2026-01-15"]);
assert.ok(!days.days[1].headings.some(heading => heading.includes("示例标题")));
const day = (await (await get("/api/logs/day?date=2026-01-15")).json()).day;
assert.ok(day.exists); assert.ok(day.version); assert.match(day.content, /## 2026-01-16/);
assert.equal((await (await get("/api/logs/day?date=2026-01-16")).json()).day.exists, false);
assert.equal((await get("/api/logs/day?date=2026-02-30")).status, 400);
assert.equal((await get("/api/logs?month=2026-13")).status, 400);
assert.deepEqual(await digests(), before);
console.log(JSON.stringify({ passed: ["authentication", "month/day navigation", "fenced content", "missing date", "invalid calendar", "source bytes preserved"] }));
